# Generated by Django 3.1.3 on 2020-11-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_addproducttocart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addProductToCart',
            new_name='Cart',
        ),
    ]
